# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_param simulator.modelsimInstallPath C:/WorkSpace/ModelSim/win32pe
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/WorkSpace/Homework_Digital_Logic/DL_BigHW/DL_BigHW.cache/wt [current_project]
set_property parent.project_path C:/WorkSpace/Homework_Digital_Logic/DL_BigHW/DL_BigHW.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib C:/WorkSpace/Homework_Digital_Logic/DL_BigHW/DL_BigHW.srcs/sources_1/new/7_segment_display.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/WorkSpace/Homework_Digital_Logic/DL_BigHW/DL_BigHW.srcs/constrs_1/new/display7.xdc
set_property used_in_implementation false [get_files C:/WorkSpace/Homework_Digital_Logic/DL_BigHW/DL_BigHW.srcs/constrs_1/new/display7.xdc]


synth_design -top display7 -part xc7a100tcsg324-1


write_checkpoint -force -noxdef display7.dcp

catch { report_utilization -file display7_utilization_synth.rpt -pb display7_utilization_synth.pb }
