######################################################################
#
# File name : combine_display7_wave.do
# Created on: Fri Dec 06 14:45:10 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
