######################################################################
#
# File name : combine_display7_simulate.do
# Created on: Fri Dec 06 14:54:00 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L unisims_ver -L unimacro_ver -L secureip -L xil_defaultlib -lib xil_defaultlib xil_defaultlib.combine_display7 xil_defaultlib.glbl

do {combine_display7_wave.do}

view wave
view structure
view signals

do {combine_display7.udo}

run 1000ns
