######################################################################
#
# File name : display7_tb_compile.do
# Created on: Thu Dec 05 13:51:45 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\WorkSpace\\ModelSim\\win32pe\\vlib work
C:\\WorkSpace\\ModelSim\\win32pe\\vlib msim

C:\\WorkSpace\\ModelSim\\win32pe\\vlib msim/xil_defaultlib

C:\\WorkSpace\\ModelSim\\win32pe\\vmap xil_defaultlib msim/xil_defaultlib

C:\\WorkSpace\\ModelSim\\win32pe\\vlog -64 -incr -work xil_defaultlib  \
"../../../DL_BigHW.srcs/sources_1/new/7_segment_display.v" \
"../../../DL_BigHW.srcs/sim_1/new/display7_tb.v" \


# compile glbl module
C:\\WorkSpace\\ModelSim\\win32pe\\vlog -work xil_defaultlib "glbl.v"

quit -force

