######################################################################
#
# File name : display7_tb_wave.do
# Created on: Thu Dec 05 13:40:29 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
