######################################################################
#
# File name : sel_display7_tb_wave.do
# Created on: Fri Dec 06 14:56:33 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
