######################################################################
#
# File name : tmp_init_tb_compile.do
# Created on: Fri Dec 06 21:46:10 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\WorkSpace\\ModelSim\\win32pe\\vlib work
C:\\WorkSpace\\ModelSim\\win32pe\\vlib msim

C:\\WorkSpace\\ModelSim\\win32pe\\vlib msim/xil_defaultlib

C:\\WorkSpace\\ModelSim\\win32pe\\vmap xil_defaultlib msim/xil_defaultlib

C:\\WorkSpace\\ModelSim\\win32pe\\vlog -64 -incr -work xil_defaultlib  \
"../../../DL_BigHW.srcs/sources_1/new/7_segment_display.v" \
"../../../DL_BigHW.srcs/sources_1/new/sel_display7.v" \
"../../../DL_BigHW.srcs/sources_1/new/tmp_init.v" \
"../../../DL_BigHW.srcs/sim_1/new/tmp_init_tb.v" \


# compile glbl module
C:\\WorkSpace\\ModelSim\\win32pe\\vlog -work xil_defaultlib "glbl.v"

quit -force

