######################################################################
#
# File name : tmp_init_tb_wave.do
# Created on: Fri Dec 06 21:34:06 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
