######################################################################
#
# File name : tmp_init_tb_simulate.do
# Created on: Fri Dec 06 21:46:14 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L unisims_ver -L unimacro_ver -L secureip -L xil_defaultlib -lib xil_defaultlib xil_defaultlib.tmp_init_tb xil_defaultlib.glbl

do {tmp_init_tb_wave.do}

view wave
view structure
view signals

do {tmp_init_tb.udo}

run 1000ns
