######################################################################
#
# File name : tri_LED_tb_simulate.do
# Created on: Thu Dec 05 14:49:49 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L unisims_ver -L unimacro_ver -L secureip -L xil_defaultlib -lib xil_defaultlib xil_defaultlib.tri_LED_tb xil_defaultlib.glbl

do {tri_LED_tb_wave.do}

view wave
view structure
view signals

do {tri_LED_tb.udo}

run 1000ns
