######################################################################
#
# File name : tri_LED_tb.udo
# Created on: Thu Dec 05 14:47:16 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
