######################################################################
#
# File name : tri_LED_compile.do
# Created on: Thu Dec 05 14:43:22 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\WorkSpace\\ModelSim\\win32pe\\vlib work
C:\\WorkSpace\\ModelSim\\win32pe\\vlib msim

C:\\WorkSpace\\ModelSim\\win32pe\\vlib msim/xil_defaultlib

C:\\WorkSpace\\ModelSim\\win32pe\\vmap xil_defaultlib msim/xil_defaultlib

C:\\WorkSpace\\ModelSim\\win32pe\\vlog -64 -incr -work xil_defaultlib  \
"../../../DL_BigHW.srcs/sources_1/new/tri_LED.v" \


# compile glbl module
C:\\WorkSpace\\ModelSim\\win32pe\\vlog -work xil_defaultlib "glbl.v"

quit -force

