######################################################################
#
# File name : tri_LED_tb_wave.do
# Created on: Thu Dec 05 14:47:16 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
